### ISSUE TITLE
Does not work with Repliacs - Kubernetes

### ISSUE THREAD

**Issue by NilsBaumgartner1994** [ChappIO/directus-extension-prometheus#4]
https://docs.directus.io/blog/understanding-kubernetes.html

When deploying with replicas we get different results when hitting /metrics

docker-compose.yaml
```yaml
version: '3.8'

services:

  # The Directus backend
  rocket-meals-directus:
    image: directus/directus:10.11.2
    deploy:
      mode: replicated
      replicas: 8
      endpoint_mode: vip # Virtual IP - https://docs.docker.com/compose/compose-file/deploy/#endpoint_mode
 ```
